import type { DefaultStyles } from '../../data-types/utility/styling';

export const defaultStyles: DefaultStyles = {
  colorMode: 'light',
  backgroundColor: 'white',
  textColor: 'black',
  componentStyles: {
    p: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      leading: 'snug',
    },
    span: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      leading: 'snug',
    },
    h1: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'bold',
      fontStyle: 'normal',
      leading: 'snug',
    },
    h2: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'bold',
      fontStyle: 'normal',
      leading: 'snug',
    },
    h3: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'bold',
      fontStyle: 'normal',
      leading: 'snug',
    },
    h4: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'semibold',
      fontStyle: 'normal',
      leading: 'snug',
    },
    h5: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'semibold',
      fontStyle: 'normal',
      leading: 'snug',
    },
    h6: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'semibold',
      fontStyle: 'normal',
      leading: 'snug',
    },
    li: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      leading: 'snug',
    },
    ol: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      leading: 'snug',
    },
    ul: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      leading: 'snug',
    },
    indent: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      leading: 'snug',
    },
    blockquote: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      leading: 'snug',
      border: 'md',
      borderColor: 'neutral',
    },
  },
};
