import type { DefaultStyles } from '../../types/style-types/index.js';
import { headingFont } from './style-variables.js';

export const defaultStyles: DefaultStyles = {
  backgroundColor: 'white',
  textColor: 'black',
  componentStyles: {
    p: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'normal',
      fontStyle: 'normal',
    },
    span: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'normal',
      fontStyle: 'normal',
    },
    h1: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '500',
      fontWeight: 'bold',
      fontFamily: headingFont,
      fontStyle: 'normal',
    },
    h2: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '500',
      fontWeight: 'bold',
      fontFamily: headingFont,
      fontStyle: 'normal',
    },
    h3: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '500',
      fontWeight: 'bold',
      fontFamily: headingFont,
      fontStyle: 'normal',
    },
    h4: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'semibold',
      fontFamily: headingFont,
      fontStyle: 'normal',
    },
    h5: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'semibold',
      fontFamily: headingFont,
      fontStyle: 'normal',
    },
    h6: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'semibold',
      fontFamily: headingFont,
      fontStyle: 'normal',
    },
    li: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'normal',
      fontStyle: 'normal',
    },
    ol: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'normal',
      fontStyle: 'normal',
      listPosition: 'inside',
      listType: 'decimal',
    },
    ul: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'normal',
      fontStyle: 'normal',
      listPosition: 'inside',
      listType: 'disc',
    },
    indent: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      fontWeight: 'normal',
      fontStyle: 'normal',
      colorTone: '700',
    },
    blockquote: {
      textSize: 'md',
      textAlign: 'left',
      textColor: 'black',
      colorTone: '700',
      fontWeight: 'normal',
      fontStyle: 'normal',
      border: 'md',
      borderColor: 'neutral',
    },
  },
};
