import type { ComponentStyles } from '@/web/style/style-types.js';
import clsx from 'clsx';

import {
  textXS,
  textSmall,
  textBase,
  textLarge,
  textXL,
  textxxl,
  text3XL,
  text4XL,
  text5XL,
  text6XL,
  text7XL,
  lineSpacingXS,
  lineSpacingSM,
  lineSpacingMD,
  lineSpacingLG,
  lineSpacingXL,
  lineSpacingxxl,
  lineIndentXS,
  lineIndentSM,
  lineIndentMD,
  lineIndentLG,
  lineIndentXL,
  lineIndentxxl,
  blockquotePaddingXS,
  blockquotePaddingSM,
  blockquotePaddingMD,
  blockquotePaddingLG,
  blockquotePaddingXL,
  blockquotePaddingxxl,
  leadingSnug,
  leadingNormal,
} from './style-variables.js';

export const componentStyles: ComponentStyles = {
  p: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    spacing: {
      xs: lineSpacingXS,
      sm: lineSpacingSM,
      md: lineSpacingMD,
      lg: lineSpacingLG,
      xl: lineSpacingXL,
      xxl: lineSpacingxxl,
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  indent: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    spacing: {
      xs: clsx(lineSpacingXS, lineIndentXS),
      sm: clsx(lineSpacingSM, lineIndentSM),
      md: clsx(lineSpacingMD, lineIndentMD),
      lg: clsx(lineSpacingLG, lineIndentLG),
      xl: clsx(lineSpacingXL, lineIndentXL),
      xxl: clsx(lineSpacingxxl, lineIndentxxl),
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  blockquote: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    spacing: {
      xs: clsx(lineSpacingXS, lineIndentXS, blockquotePaddingXS),
      sm: clsx(lineSpacingSM, lineIndentSM, blockquotePaddingSM),
      md: clsx(lineSpacingMD, lineIndentMD, blockquotePaddingMD),
      lg: clsx(lineSpacingLG, lineIndentLG, blockquotePaddingLG),
      xl: clsx(lineSpacingXL, lineIndentXL, blockquotePaddingXL),
      xxl: clsx(lineSpacingxxl, lineIndentxxl, blockquotePaddingxxl),
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    border: {
      xs: 'border-l-2',
      sm: 'border-l-4',
      md: 'border-l-4',
      lg: 'border-l-4',
      xl: 'border-l-6',
      xxl: 'border-l-4',
    },
    borderColor: {
      primary: 'border-primary-300',
      secondary: 'border-secondary-300',
      accent: 'border-accent-300',
      'secondary-accent': 'border-secondary-accent-300',
      neutral: 'border-neutral-300',
      white: 'border-white',
      black: 'border-black',
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  span: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    spacing: {
      xs: '',
      sm: '',
      md: '',
      lg: '',
      xl: '',
      xxl: '',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },

  h1: {
    fontSize: {
      xs: textxxl,
      sm: text3XL,
      md: text4XL,
      lg: text5XL,
      xl: text6XL,
      xxl: text7XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      xxl: 'mb-3',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingSnug,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h2: {
    fontSize: {
      xs: textXL,
      sm: textxxl,
      md: text3XL,
      lg: text4XL,
      xl: text5XL,
      xxl: text6XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      xxl: 'mb-3',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingSnug,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h3: {
    fontSize: {
      xs: textLarge,
      sm: textXL,
      md: textxxl,
      lg: text3XL,
      xl: text4XL,
      xxl: text5XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      xxl: 'mb-3',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h4: {
    fontSize: {
      xs: textBase,
      sm: textLarge,
      md: textXL,
      lg: textxxl,
      xl: text3XL,
      xxl: text4XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      xxl: 'mb-3',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h5: {
    fontSize: {
      xs: textBase,
      sm: textLarge,
      md: textXL,
      lg: textxxl,
      xl: text3XL,
      xxl: text4XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      xxl: 'mb-3',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h6: {
    fontSize: {
      xs: textSmall,
      sm: textBase,
      md: textLarge,
      lg: textXL,
      xl: textxxl,
      xxl: text3XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      xxl: 'mb-3',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  li: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      xxl: 'mb-3',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  ol: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
    spacing: {
      xs: 'mb-4 md:mb-6',
      sm: 'mb-4 md:mb-6',
      md: 'mb-4 md:mb-6',
      lg: 'mb-6 md:mb-8',
      xl: 'mb-6 md:mb-8',
      xxl: 'mb-6 md:mb-8',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
  },
  ul: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    spacing: {
      xs: 'mb-4 md:mb-6',
      sm: 'mb-4 md:mb-6',
      md: 'mb-4 md:mb-6',
      lg: 'mb-6 md:mb-8',
      xl: 'mb-6 md:mb-8',
      xxl: 'mb-6 md:mb-8',
    },
    leading: {
      xs: leadingNormal,
      sm: leadingNormal,
      md: leadingNormal,
      lg: leadingSnug,
      xl: leadingSnug,
      xxl: leadingSnug,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  button: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      xxl: textxxl,
    },
    spacing: {
      xs: 'px-3 py-2',
      sm: 'px-4 py-2',
      md: 'px-4 py-2',
      lg: 'px-6 py-2',
      xl: 'px-6 py-3',
      xxl: 'px-8 py-3',
    },
  },
};
