import type { ComponentStyles } from '@/web/style/style-types.js';
import clsx from 'clsx';

import {
  textXS,
  textSmall,
  textBase,
  textLarge,
  textXL,
  text2XL,
  text3XL,
  text4XL,
  text5XL,
  text6XL,
  text7XL,
  lineSpacingXS,
  lineSpacingSM,
  lineSpacingMD,
  lineSpacingLG,
  lineSpacingXL,
  lineSpacing2XL,
  lineIndentXS,
  lineIndentSM,
  lineIndentMD,
  lineIndentLG,
  lineIndentXL,
  lineIndent2XL,
  blockquotePaddingXS,
  blockquotePaddingSM,
  blockquotePaddingMD,
  blockquotePaddingLG,
  blockquotePaddingXL,
  blockquotePadding2XL,
} from './style-variables.js';

export const componentStyles: ComponentStyles = {
  p: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: lineSpacingXS,
      sm: lineSpacingSM,
      md: lineSpacingMD,
      lg: lineSpacingLG,
      xl: lineSpacingXL,
      '2xl': lineSpacing2XL,
    },
    // leading: {
    //   xs: 'leading-snug md:leading-normal',
    //   sm: 'leading-snug md:leading-normal',
    //   md: 'leading-snug md:leading-normal',
    //   lg: 'leading-snug md:leading-normal',
    //   xl: 'leading-snug md:leading-normal',
    //   '2xl': 'leading-snug md:leading-normal',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  indent: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: clsx(lineSpacingXS, lineIndentXS),
      sm: clsx(lineSpacingSM, lineIndentSM),
      md: clsx(lineSpacingMD, lineIndentMD),
      lg: clsx(lineSpacingLG, lineIndentLG),
      xl: clsx(lineSpacingXL, lineIndentXL),
      '2xl': clsx(lineSpacing2XL, lineIndent2XL),
    },
    // leading: {
    //   xs: 'leading-snug md:leading-normal',
    //   sm: 'leading-snug md:leading-normal',
    //   md: 'leading-snug md:leading-normal',
    //   lg: 'leading-snug md:leading-normal',
    //   xl: 'leading-snug md:leading-normal',
    //   '2xl': 'leading-snug md:leading-normal',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  blockquote: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: clsx(lineSpacingXS, lineIndentXS, blockquotePaddingXS),
      sm: clsx(lineSpacingSM, lineIndentSM, blockquotePaddingSM),
      md: clsx(lineSpacingMD, lineIndentMD, blockquotePaddingMD),
      lg: clsx(lineSpacingLG, lineIndentLG, blockquotePaddingLG),
      xl: clsx(lineSpacingXL, lineIndentXL, blockquotePaddingXL),
      '2xl': clsx(lineSpacing2XL, lineIndent2XL, blockquotePadding2XL),
    },
    border: {
      xs: 'border-l-2',
      sm: 'border-l-4',
      md: 'border-l-4',
      lg: 'border-l-4',
      xl: 'border-l-6',
      '2xl': 'border-l-4',
    },
    borderColor: {
      primary: 'border-primary-300',
      secondary: 'border-secondary-300',
      accent: 'border-accent-300',
      'secondary-accent': 'border-secondary-accent-300',
      neutral: 'border-neutral-300',
      white: 'border-white',
      black: 'border-black',
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  span: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: '',
      sm: '',
      md: '',
      lg: '',
      xl: '',
      '2xl': '',
    },
    // leading: {
    //   xs: 'leading-snug md:leading-normal',
    //   sm: 'leading-snug md:leading-normal',
    //   md: 'leading-snug md:leading-normal',
    //   lg: 'leading-snug md:leading-normal',
    //   xl: 'leading-snug md:leading-normal',
    //   '2xl': 'leading-snug md:leading-normal',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },

  h1: {
    fontSize: {
      xs: text2XL,
      sm: text3XL,
      md: text4XL,
      lg: text5XL,
      xl: text6XL,
      '2xl': text7XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h2: {
    fontSize: {
      xs: textXL,
      sm: text2XL,
      md: text3XL,
      lg: text4XL,
      xl: text5XL,
      '2xl': text6XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h3: {
    fontSize: {
      xs: textLarge,
      sm: textXL,
      md: text2XL,
      lg: text3XL,
      xl: text4XL,
      '2xl': text5XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h4: {
    fontSize: {
      xs: textBase,
      sm: textLarge,
      md: textXL,
      lg: text2XL,
      xl: text3XL,
      '2xl': text4XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h5: {
    fontSize: {
      xs: textBase,
      sm: textLarge,
      md: textXL,
      lg: text2XL,
      xl: text3XL,
      '2xl': text4XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h6: {
    fontSize: {
      xs: textSmall,
      sm: textBase,
      md: textLarge,
      lg: textXL,
      xl: text2XL,
      '2xl': text3XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  li: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  ol: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
    spacing: {
      xs: 'mb-4 md:mb-6',
      sm: 'mb-4 md:mb-6',
      md: 'mb-4 md:mb-6',
      lg: 'mb-6 md:mb-8',
      xl: 'mb-6 md:mb-8',
      '2xl': 'mb-6 md:mb-8',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
  },
  ul: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-4 md:mb-6',
      sm: 'mb-4 md:mb-6',
      md: 'mb-4 md:mb-6',
      lg: 'mb-6 md:mb-8',
      xl: 'mb-6 md:mb-8',
      '2xl': 'mb-6 md:mb-8',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  button: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'px-3 py-2',
      sm: 'px-4 py-2',
      md: 'px-4 py-2',
      lg: 'px-6 py-2',
      xl: 'px-6 py-3',
      '2xl': 'px-8 py-3',
    },
  },
};
