import type { ComponentStyles } from '@/web/style/style-types';

const textXS = 'text-xs md:text-sm';
const textSmall = 'text-sm md:text-base';
const textBase = 'text-base';
const textLarge = 'text-lg md:text-xl';
const textXL = 'text-xl md:text-2xl';
const text2XL = 'text-2xl md:text-3xl lg:text-4xl';
const text3XL = 'text-3xl md:text-4xl lg:text-5xl';
const text4XL = 'text-4xl md:text-5xl lg:text-6xl';
const text5XL = 'text-5xl md:text-6xl lg:text-7xl';
const text6XL = 'text-6xl md:text-7xl lg:text-8xl';
const text7XL = 'text-7xl md:text-8xl lg:text-9xl';

export const componentStyles: ComponentStyles = {
  p: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-4 md:mb-6',
      sm: 'mb-4 md:mb-6',
      md: 'mb-4 md:mb-6',
      lg: 'mb-6 md:mb-8',
      xl: 'mb-6 md:mb-8',
      '2xl': 'mb-6 md:mb-8',
    },
    // leading: {
    //   xs: 'leading-snug md:leading-normal',
    //   sm: 'leading-snug md:leading-normal',
    //   md: 'leading-snug md:leading-normal',
    //   lg: 'leading-snug md:leading-normal',
    //   xl: 'leading-snug md:leading-normal',
    //   '2xl': 'leading-snug md:leading-normal',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  indent: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-4 md:mb-6 ml-4',
      sm: 'mb-4 md:mb-6 ml-4',
      md: 'mb-4 md:mb-6 ml-4',
      lg: 'mb-6 md:mb-8 ml-4',
      xl: 'mb-6 md:mb-8 ml-4',
      '2xl': 'mb-6 md:mb-8 ml-4',
    },
    // leading: {
    //   xs: 'leading-snug md:leading-normal',
    //   sm: 'leading-snug md:leading-normal',
    //   md: 'leading-snug md:leading-normal',
    //   lg: 'leading-snug md:leading-normal',
    //   xl: 'leading-snug md:leading-normal',
    //   '2xl': 'leading-snug md:leading-normal',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  blockquote: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-4 md:mb-6 pl-2 ml-1',
      sm: 'mb-4 md:mb-6 pl-2 ml-1',
      md: 'mb-4 md:mb-6 pl-3 ml-1',
      lg: 'mb-6 md:mb-8 pl-3 ml-1',
      xl: 'mb-6 md:mb-8 pl-3 ml-1',
      '2xl': 'mb-6 md:mb-8 pl-3 ml-1',
    },
    border: {
      xs: 'border-l-2',
      sm: 'border-l-4',
      md: 'border-l-4',
      lg: 'border-l-4',
      xl: 'border-l-6',
      '2xl': 'border-l-4',
    },
    borderColor: {
      primary: 'border-primary-300',
      secondary: 'border-secondary-300',
      accent: 'border-accent-300',
      'secondary-accent': 'border-secondary-accent-300',
      neutral: 'border-neutral-300',
      white: 'border-white',
      black: 'border-black',
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  span: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-snug md:leading-normal',
    //   sm: 'leading-snug md:leading-normal',
    //   md: 'leading-snug md:leading-normal',
    //   lg: 'leading-snug md:leading-normal',
    //   xl: 'leading-snug md:leading-normal',
    //   '2xl': 'leading-snug md:leading-normal',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h1: {
    fontSize: {
      xs: text2XL,
      sm: text3XL,
      md: text4XL,
      lg: text5XL,
      xl: text6XL,
      '2xl': text7XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h2: {
    fontSize: {
      xs: textXL,
      sm: text2XL,
      md: text3XL,
      lg: text4XL,
      xl: text5XL,
      '2xl': text6XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h3: {
    fontSize: {
      xs: textLarge,
      sm: textXL,
      md: text2XL,
      lg: text3XL,
      xl: text4XL,
      '2xl': text5XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h4: {
    fontSize: {
      xs: textBase,
      sm: textLarge,
      md: textXL,
      lg: text2XL,
      xl: text3XL,
      '2xl': text4XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h5: {
    fontSize: {
      xs: textBase,
      sm: textLarge,
      md: textXL,
      lg: text2XL,
      xl: text3XL,
      '2xl': text4XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  h6: {
    fontSize: {
      xs: textSmall,
      sm: textBase,
      md: textLarge,
      lg: textXL,
      xl: text2XL,
      '2xl': text3XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  li: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-3',
      sm: 'mb-3',
      md: 'mb-3',
      lg: 'mb-3',
      xl: 'mb-3',
      '2xl': 'mb-3',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  ol: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
    spacing: {
      xs: 'mb-4 md:mb-6',
      sm: 'mb-4 md:mb-6',
      md: 'mb-4 md:mb-6',
      lg: 'mb-6 md:mb-8',
      xl: 'mb-6 md:mb-8',
      '2xl': 'mb-6 md:mb-8',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
  },
  ul: {
    fontSize: {
      xs: textXS,
      sm: textSmall,
      md: textBase,
      lg: textLarge,
      xl: textXL,
      '2xl': text2XL,
    },
    spacing: {
      xs: 'mb-4 md:mb-6',
      sm: 'mb-4 md:mb-6',
      md: 'mb-4 md:mb-6',
      lg: 'mb-6 md:mb-8',
      xl: 'mb-6 md:mb-8',
      '2xl': 'mb-6 md:mb-8',
    },
    // leading: {
    //   xs: 'leading-tight',
    //   sm: 'leading-snug',
    //   md: 'leading-normal',
    //   lg: 'leading-relaxed',
    //   xl: 'leading-loose',
    //   '2xl': 'leading-loose',
    // },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
};
