import { StyleGuide } from '@/web/style/style-types.js';
import { componentStyles } from './element-styles.js';
import { defaultStyles } from './default-styles.js';
import { spacingStyles } from './spacing-styles.js';
import {
  // Background color variables
  primaryDarkestBg,
  primaryDarkBg,
  primaryDeepBg,
  primaryMediumBg,
  primarySurfaceBg,
  primaryLightBg,
  secondaryDarkestBg,
  secondaryDarkBg,
  secondaryDeepBg,
  secondaryMediumBg,
  secondarySurfaceBg,
  secondaryLightBg,
  accentDarkestBg,
  accentDarkBg,
  accentDeepBg,
  accentMediumBg,
  accentSurfaceBg,
  accentLightBg,
  secondaryAccentDarkestBg,
  secondaryAccentDarkBg,
  secondaryAccentDeepBg,
  secondaryAccentMediumBg,
  secondaryAccentSurfaceBg,
  secondaryAccentLightBg,
  neutralDarkestBg,
  neutralDarkBg,
  neutralDeepBg,
  neutralMediumBg,
  neutralSurfaceBg,
  neutralLightBg,
  whiteDarkestBg,
  whiteDarkBg,
  whiteDeepBg,
  whiteMediumBg,
  whiteSurfaceBg,
  whiteLightBg,
  blackDarkestBg,
  blackDarkBg,
  blackDeepBg,
  blackMediumBg,
  blackSurfaceBg,
  blackLightBg,
  // Text color variables
  primaryTextDarkest,
  primaryTextDark,
  primaryTextDeep,
  primaryTextMedium,
  primaryTextSurface,
  primaryTextLight,
  secondaryTextDarkest,
  secondaryTextDark,
  secondaryTextDeep,
  secondaryTextMedium,
  secondaryTextSurface,
  secondaryTextLight,
  accentTextDarkest,
  accentTextDark,
  accentTextDeep,
  accentTextMedium,
  accentTextSurface,
  accentTextLight,
  secondaryAccentTextDarkest,
  secondaryAccentTextDark,
  secondaryAccentTextDeep,
  secondaryAccentTextMedium,
  secondaryAccentTextSurface,
  secondaryAccentTextLight,
  neutralTextDarkest,
  neutralTextDark,
  neutralTextDeep,
  neutralTextMedium,
  neutralTextSurface,
  neutralTextLight,
  whiteTextDarkest,
  whiteTextDark,
  whiteTextDeep,
  whiteTextMedium,
  whiteTextSurface,
  whiteTextLight,
  blackTextDarkest,
  blackTextDark,
  blackTextDeep,
  blackTextMedium,
  blackTextSurface,
  blackTextLight,
} from './style-variables.js';

export const styleGuide: StyleGuide = {
  defaultStyles,
  bgColor: {
    primary: {
      darkest: primaryDarkestBg,
      dark: primaryDarkBg,
      deep: primaryDeepBg,
      medium: primaryMediumBg,
      surface: primarySurfaceBg,
      light: primaryLightBg,
    },
    secondary: {
      darkest: secondaryDarkestBg,
      dark: secondaryDarkBg,
      deep: secondaryDeepBg,
      medium: secondaryMediumBg,
      surface: secondarySurfaceBg,
      light: secondaryLightBg,
    },
    accent: {
      darkest: accentDarkestBg,
      dark: accentDarkBg,
      deep: accentDeepBg,
      medium: accentMediumBg,
      surface: accentSurfaceBg,
      light: accentLightBg,
    },
    'secondary-accent': {
      darkest: secondaryAccentDarkestBg,
      dark: secondaryAccentDarkBg,
      deep: secondaryAccentDeepBg,
      medium: secondaryAccentMediumBg,
      surface: secondaryAccentSurfaceBg,
      light: secondaryAccentLightBg,
    },
    neutral: {
      darkest: neutralDarkestBg,
      dark: neutralDarkBg,
      deep: neutralDeepBg,
      medium: neutralMediumBg,
      surface: neutralSurfaceBg,
      light: neutralLightBg,
    },
    white: {
      darkest: whiteDarkestBg,
      dark: whiteDarkBg,
      deep: whiteDeepBg,
      medium: whiteMediumBg,
      surface: whiteSurfaceBg,
      light: whiteLightBg,
    },
    black: {
      darkest: blackDarkestBg,
      dark: blackDarkBg,
      deep: blackDeepBg,
      medium: blackMediumBg,
      surface: blackSurfaceBg,
      light: blackLightBg,
    },
  },
  textColor: {
    primary: {
      darkest: primaryTextDarkest,
      dark: primaryTextDark,
      deep: primaryTextDeep,
      medium: primaryTextMedium,
      surface: primaryTextSurface,
      light: primaryTextLight,
    },
    secondary: {
      darkest: secondaryTextDarkest,
      dark: secondaryTextDark,
      deep: secondaryTextDeep,
      medium: secondaryTextMedium,
      surface: secondaryTextSurface,
      light: secondaryTextLight,
    },
    accent: {
      darkest: accentTextDarkest,
      dark: accentTextDark,
      deep: accentTextDeep,
      medium: accentTextMedium,
      surface: accentTextSurface,
      light: accentTextLight,
    },
    'secondary-accent': {
      darkest: secondaryAccentTextDarkest,
      dark: secondaryAccentTextDark,
      deep: secondaryAccentTextDeep,
      medium: secondaryAccentTextMedium,
      surface: secondaryAccentTextSurface,
      light: secondaryAccentTextLight,
    },
    neutral: {
      darkest: neutralTextDarkest,
      dark: neutralTextDark,
      deep: neutralTextDeep,
      medium: neutralTextMedium,
      surface: neutralTextSurface,
      light: neutralTextLight,
    },
    white: {
      darkest: whiteTextDarkest,
      dark: whiteTextDark,
      deep: whiteTextDeep,
      medium: whiteTextMedium,
      surface: whiteTextSurface,
      light: whiteTextLight,
    },
    black: {
      darkest: blackTextDarkest,
      dark: blackTextDark,
      deep: blackTextDeep,
      medium: blackTextMedium,
      surface: blackTextSurface,
      light: blackTextLight,
    },
  },
  fontWeight: {
    thin: 'font-thin',
    extralight: 'font-extralight',
    light: 'font-light',
    normal: 'font-normal',
    medium: 'font-medium',
    semibold: 'font-semibold',
    bold: 'font-bold',
    extrabold: 'font-extrabold',
    black: 'font-black',
  },
  fontStyle: {
    normal: 'non-italic',
    italic: 'italic',
  },
  leading: {
    none: 'leading-none',
    tight: 'leading-tight',
    snug: 'leading-snug',
    normal: 'leading-normal',
    relaxed: 'leading-relaxed',
    loose: 'leading-loose',
  },
  listType: {
    none: 'list-none',
    disc: 'list-disc',
    decimal: 'list-decimal',
  },
  listPosition: {
    inside: 'list-inside',
    outside: 'list-outside',
  },
  componentStyles,
  rounding: {
    none: 'rounded-none',
    sm: 'rounded',
    md: 'rounded-md',
    lg: 'rounded-lg',
    full: 'rounded-full',
  },
  spacing: spacingStyles,
};
