import { StyleGuide } from '../../types/style-types/index.js';
import { componentStyles } from './element-styles.js';
import { defaultStyles } from './default-styles.js';
import { spacingStyles } from './spacing-styles.js';
import {
  // Background color variables
  primaryDarkestBg,
  primaryDarkBg,
  primaryShadeBg,
  primaryMediumBg,
  primarySoftBg,
  primaryLightBg,
  primaryLightestBg,
  secondaryDarkestBg,
  secondaryDarkBg,
  secondaryShadeBg,
  secondaryMediumBg,
  secondarySoftBg,
  secondaryLightBg,
  secondaryLightestBg,
  accentDarkestBg,
  accentDarkBg,
  accentShadeBg,
  accentMediumBg,
  accentSoftBg,
  accentLightBg,
  accentLightestBg,
  secondaryAccentDarkestBg,
  secondaryAccentDarkBg,
  secondaryAccentShadeBg,
  secondaryAccentMediumBg,
  secondaryAccentSoftBg,
  secondaryAccentLightBg,
  secondaryAccentLightestBg,
  neutralDarkestBg,
  neutralDarkBg,
  neutralShadeBg,
  neutralMediumBg,
  neutralSoftBg,
  neutralLightBg,
  neutralLightestBg,
  whiteBg,
  blackBg,
  // Text color variables
  primaryTextDarkest,
  primaryTextDark,
  primaryTextShade,
  primaryTextMedium,
  primaryTextSoft,
  primaryTextLight,
  primaryTextLightest,
  secondaryTextDarkest,
  secondaryTextDark,
  secondaryTextShade,
  secondaryTextMedium,
  secondaryTextSoft,
  secondaryTextLight,
  secondaryTextLightest,
  accentTextDarkest,
  accentTextDark,
  accentTextShade,
  accentTextMedium,
  accentTextSoft,
  accentTextLight,
  accentTextLightest,
  secondaryAccentTextDarkest,
  secondaryAccentTextDark,
  secondaryAccentTextShade,
  secondaryAccentTextMedium,
  secondaryAccentTextSoft,
  secondaryAccentTextLight,
  secondaryAccentTextLightest,
  neutralTextDarkest,
  neutralTextDark,
  neutralTextShade,
  neutralTextMedium,
  neutralTextSoft,
  neutralTextLight,
  neutralTextLightest,
  whiteText,
  blackText,
  // Opacity variables
  opacityNone,
  opacityDarkest,
  opacityDark,
  opacityShade,
  opacityMedium,
  opacitySoft,
  opacityLight,
  opacityLightest,
  opacityFull,
  leadingNone,
  leadingTight,
  leadingSnug,
  leadingNormal,
  leadingRelaxed,
  leadingLoose,
} from './style-variables.js';

export const styleGuide: StyleGuide = {
  defaultStyles,
  bgColor: {
    primary: {
      darkest: primaryDarkestBg,
      dark: primaryDarkBg,
      shade: primaryShadeBg,
      medium: primaryMediumBg,
      soft: primarySoftBg,
      light: primaryLightBg,
      lightest: primaryLightestBg,
    },
    secondary: {
      darkest: secondaryDarkestBg,
      dark: secondaryDarkBg,
      shade: secondaryShadeBg,
      medium: secondaryMediumBg,
      soft: secondarySoftBg,
      light: secondaryLightBg,
      lightest: secondaryLightestBg,
    },
    accent: {
      darkest: accentDarkestBg,
      dark: accentDarkBg,
      shade: accentShadeBg,
      medium: accentMediumBg,
      soft: accentSoftBg,
      light: accentLightBg,
      lightest: accentLightestBg,
    },
    'secondary-accent': {
      darkest: secondaryAccentDarkestBg,
      dark: secondaryAccentDarkBg,
      shade: secondaryAccentShadeBg,
      medium: secondaryAccentMediumBg,
      soft: secondaryAccentSoftBg,
      light: secondaryAccentLightBg,
      lightest: secondaryAccentLightestBg,
    },
    neutral: {
      darkest: neutralDarkestBg,
      dark: neutralDarkBg,
      shade: neutralShadeBg,
      medium: neutralMediumBg,
      soft: neutralSoftBg,
      light: neutralLightBg,
      lightest: neutralLightestBg,
    },
    white: {
      darkest: whiteBg,
      dark: whiteBg,
      shade: whiteBg,
      medium: whiteBg,
      soft: whiteBg,
      light: whiteBg,
      lightest: whiteBg,
    },
    black: {
      darkest: blackBg,
      dark: blackBg,
      shade: blackBg,
      medium: blackBg,
      soft: blackBg,
      light: blackBg,
      lightest: blackBg,
    },
  },
  textColor: {
    primary: {
      darkest: primaryTextDarkest,
      dark: primaryTextDark,
      shade: primaryTextShade,
      medium: primaryTextMedium,
      soft: primaryTextSoft,
      light: primaryTextLight,
      lightest: primaryTextLightest,
    },
    secondary: {
      darkest: secondaryTextDarkest,
      dark: secondaryTextDark,
      shade: secondaryTextShade,
      medium: secondaryTextMedium,
      soft: secondaryTextSoft,
      light: secondaryTextLight,
      lightest: secondaryTextLightest,
    },
    accent: {
      darkest: accentTextDarkest,
      dark: accentTextDark,
      shade: accentTextShade,
      medium: accentTextMedium,
      soft: accentTextSoft,
      light: accentTextLight,
      lightest: accentTextLightest,
    },
    'secondary-accent': {
      darkest: secondaryAccentTextDarkest,
      dark: secondaryAccentTextDark,
      shade: secondaryAccentTextShade,
      medium: secondaryAccentTextMedium,
      soft: secondaryAccentTextSoft,
      light: secondaryAccentTextLight,
      lightest: secondaryAccentTextLightest,
    },
    neutral: {
      darkest: neutralTextDarkest,
      dark: neutralTextDark,
      shade: neutralTextShade,
      medium: neutralTextMedium,
      soft: neutralTextSoft,
      light: neutralTextLight,
      lightest: neutralTextLightest,
    },
    white: {
      darkest: whiteText,
      dark: whiteText,
      shade: whiteText,
      medium: whiteText,
      soft: whiteText,
      light: whiteText,
      lightest: whiteText,
    },
    black: {
      darkest: blackText,
      dark: blackText,
      shade: blackText,
      medium: blackText,
      soft: blackText,
      light: blackText,
      lightest: blackText,
    },
  },
  fontWeight: {
    thin: 'font-thin',
    extralight: 'font-extralight',
    light: 'font-light',
    normal: 'font-normal',
    medium: 'font-medium',
    semibold: 'font-semibold',
    bold: 'font-bold',
    extrabold: 'font-extrabold',
    black: 'font-black',
  },
  fontStyle: {
    normal: 'non-italic',
    italic: 'italic',
  },
  leading: {
    none: leadingNone,
    tight: leadingTight,
    snug: leadingSnug,
    normal: leadingNormal,
    relaxed: leadingRelaxed,
    loose: leadingLoose,
  },
  listType: {
    none: 'list-none',
    disc: 'list-disc',
    decimal: 'list-decimal',
  },
  listPosition: {
    inside: 'list-inside',
    outside: 'list-outside',
  },
  componentStyles,
  rounding: {
    none: 'rounded-none',
    sm: 'rounded',
    md: 'rounded-md',
    lg: 'rounded-lg',
    full: 'rounded-full',
  },
  opacity: {
    none: opacityNone,
    darkest: opacityDarkest,
    dark: opacityDark,
    shade: opacityShade,
    medium: opacityMedium,
    soft: opacitySoft,
    light: opacityLight,
    lightest: opacityLightest,
    full: opacityFull,
  },
  spacing: spacingStyles,
};
